Fix a unicode bug in Tempita
 * because utf-8 encoding was not propagated the template
 engine had raised an error:

 TypeError: cannot use a string pattern on a bytes-like object

 This is a fix without fixing Tempita upstream.